import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/NavBar";
import { ThemeProvider } from "next-themes";
import Footer from "../components/Footer";
import Divider from "@/components/Divider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-50 dark:bg-primary-900 dark:text-white font-text text-black flex flex-col min-h-screen">
        {/* Navbar */}
        <ThemeProvider attribute="class" defaultTheme="system">
          <Navbar />

          {/* Contenu principal qui prend tout l’espace restant */}
          <main className="flex-1  max-w-7xl mx-auto px-4 sm:px-6 lg:px-10 w-full mt-20">
            {children}
          </main>
          {/* Footer qui reste en bas */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
